name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker Test image
      run: docker build --tag flattr-image --build-arg CACHEBUST=$(date +%s) . --file Dockerfile.test
